/**
 * COMPREHENSIVE LANGUAGE LAB LEXICONS
 * 1900+ entries across Neo-Latin, Sanskrit, Quenya, and Evolved Esperanto.
 *
 * TAG SCHEMA:
 * Neo-Latin: n.[m|f|n].[1-5][i], adj.12, adj.3, v.[1-4]
 * Sanskrit:  n.[m|f|n].[a|ā|i|u|ī|ū|c], v.[1-10][p|ā]
 * Quenya:    n.v (vocalic), n.c (consonantal), adj + att:[Source]
 * Esperanto: n, adj, v, adv, prep, conj, interj
 */

export interface LexiconEntry {
  w: string; // word (headword)
  g: string; // grammar tags (pos.class)
  e: string; // english gloss
  stem?: string; // optional stem override
  att?: string; // Quenya source citation
}

// ============================================================================
// NEO-LATIN (600 entries)
// ============================================================================
export const neoLatinLexicon: LexiconEntry[] = [
  // People & Family
  { w: 'homo', g: 'n.m.3', e: 'human', stem: 'homin' },
  { w: 'vir', g: 'n.m.2', e: 'man' },
  { w: 'mulier', g: 'n.f.3', e: 'woman', stem: 'mulier' },
  { w: 'puer', g: 'n.m.2', e: 'boy' },
  { w: 'puella', g: 'n.f.1', e: 'girl' },
  { w: 'pater', g: 'n.m.3', e: 'father', stem: 'patr' },
  { w: 'mater', g: 'n.f.3', e: 'mother', stem: 'matr' },
  { w: 'filius', g: 'n.m.2', e: 'son' },
  { w: 'filia', g: 'n.f.1', e: 'daughter' },
  { w: 'frater', g: 'n.m.3', e: 'brother', stem: 'fratr' },
  { w: 'soror', g: 'n.f.3', e: 'sister', stem: 'soror' },
  { w: 'amicus', g: 'n.m.2', e: 'friend' },
  { w: 'amica', g: 'n.f.1', e: 'female friend' },
  { w: 'rex', g: 'n.m.3', e: 'king', stem: 'reg' },
  { w: 'regina', g: 'n.f.1', e: 'queen' },
  { w: 'civis', g: 'n.m.3i', e: 'citizen' },
  { w: 'hostis', g: 'n.m.3i', e: 'enemy' },
  { w: 'magister', g: 'n.m.2', e: 'teacher/master' },
  { w: 'discipulus', g: 'n.m.2', e: 'student' },
  { w: 'miles', g: 'n.m.3', e: 'soldier', stem: 'milit' },
  // Mind & Spirit
  { w: 'animus', g: 'n.m.2', e: 'soul/mind' },
  { w: 'mens', g: 'n.f.3i', e: 'mind', stem: 'ment' },
  { w: 'ratio', g: 'n.f.3', e: 'reason', stem: 'ration' },
  { w: 'sapientia', g: 'n.f.1', e: 'wisdom' },
  { w: 'veritas', g: 'n.f.3', e: 'truth', stem: 'veritat' },
  { w: 'virtus', g: 'n.f.3', e: 'virtue', stem: 'virtut' },
  { w: 'malum', g: 'n.n.2', e: 'evil' },
  { w: 'bonum', g: 'n.n.2', e: 'good' },
  { w: 'amor', g: 'n.m.3', e: 'love', stem: 'amor' },
  { w: 'odium', g: 'n.n.2', e: 'hatred' },
  { w: 'irae', g: 'n.f.1', e: 'anger' },
  { w: 'gaudium', g: 'n.n.2', e: 'joy' },
  { w: 'tristitia', g: 'n.f.1', e: 'sadness' },
  { w: 'spes', g: 'n.f.3i', e: 'hope', stem: 'spe' },
  { w: 'timor', g: 'n.m.3', e: 'fear', stem: 'timor' },
  { w: 'desperatio', g: 'n.f.3', e: 'despair', stem: 'desperation' },
  { w: 'fiducia', g: 'n.f.1', e: 'trust/confidence' },
  { w: 'dubitatio', g: 'n.f.3', e: 'doubt', stem: 'dubitatio' },
  // Abstract Concepts
  { w: 'pax', g: 'n.f.3', e: 'peace', stem: 'pac' },
  { w: 'bellum', g: 'n.n.2', e: 'war' },
  { w: 'victoria', g: 'n.f.1', e: 'victory' },
  { w: 'fragilitas', g: 'n.f.3', e: 'fragility', stem: 'fragil' },
  { w: 'tempus', g: 'n.n.3', e: 'time', stem: 'tempor' },
  { w: 'aeternitas', g: 'n.f.3', e: 'eternity', stem: 'aeternitat' },
  { w: 'mors', g: 'n.f.3', e: 'death', stem: 'mort' },
  { w: 'vitae', g: 'n.f.1', e: 'life' },
  { w: 'corpus', g: 'n.n.3', e: 'body', stem: 'corpor' },
  { w: 'anima', g: 'n.f.1', e: 'soul' },
  { w: 'voluntas', g: 'n.f.3', e: 'will', stem: 'voluntat' },
  { w: 'potentia', g: 'n.f.1', e: 'power/potential' },
  { w: 'actio', g: 'n.f.3', e: 'action', stem: 'action' },
  { w: 'passio', g: 'n.f.3', e: 'passion', stem: 'passion' },
  { w: 'ars', g: 'n.f.3', e: 'art/skill', stem: 'art' },
  { w: 'scientia', g: 'n.f.1', e: 'science/knowledge' },
  { w: 'doctrina', g: 'n.f.1', e: 'doctrine/teaching' },
  { w: 'lex', g: 'n.f.3', e: 'law', stem: 'leg' },
  { w: 'iustitia', g: 'n.f.1', e: 'justice' },
  { w: 'libertas', g: 'n.f.3', e: 'freedom', stem: 'libertat' },
  { w: 'servitium', g: 'n.n.2', e: 'slavery' },
  // Body Parts
  { w: 'caput', g: 'n.n.3', e: 'head', stem: 'capit' },
  { w: 'os', g: 'n.n.3', e: 'mouth', stem: 'or' },
  { w: 'lingua', g: 'n.f.1', e: 'tongue' },
  { w: 'dentes', g: 'n.m.3', e: 'teeth', stem: 'dent' },
  { w: 'oculus', g: 'n.m.2', e: 'eye' },
  { w: 'auris', g: 'n.f.3i', e: 'ear' },
  { w: 'nasus', g: 'n.m.2', e: 'nose' },
  { w: 'cor', g: 'n.n.3', e: 'heart', stem: 'cord' },
  { w: 'pulmones', g: 'n.m.3', e: 'lungs', stem: 'pulmon' },
  { w: 'stomachus', g: 'n.m.2', e: 'stomach' },
  { w: 'ventriculus', g: 'n.m.2', e: 'belly' },
  { w: 'hepar', g: 'n.n.3', e: 'liver', stem: 'hepat' },
  { w: 'sanguis', g: 'n.m.3i', e: 'blood' },
  { w: 'os', g: 'n.n.3', e: 'bone', stem: 'oss' },
  { w: 'caro', g: 'n.f.3', e: 'flesh', stem: 'carn' },
  { w: 'musculus', g: 'n.m.2', e: 'muscle' },
  { w: 'brachia', g: 'n.n.2', e: 'arm' },
  { w: 'manus', g: 'n.f.3', e: 'hand', stem: 'man' },
  { w: 'digitus', g: 'n.m.2', e: 'finger' },
  { w: 'unguis', g: 'n.m.3i', e: 'nail/claw' },
  { w: 'genu', g: 'n.n.3i', e: 'knee' },
  { w: 'pes', g: 'n.m.3', e: 'foot', stem: 'ped' },
  // Nature & Elements
  { w: 'terra', g: 'n.f.1', e: 'earth' },
  { w: 'caelum', g: 'n.n.2', e: 'sky/heaven' },
  { w: 'sol', g: 'n.m.3', e: 'sun', stem: 'sol' },
  { w: 'luna', g: 'n.f.1', e: 'moon' },
  { w: 'stella', g: 'n.f.1', e: 'star' },
  { w: 'mare', g: 'n.n.3i', e: 'sea' },
  { w: 'oceanus', g: 'n.m.2', e: 'ocean' },
  { w: 'flumen', g: 'n.n.3', e: 'river', stem: 'flumin' },
  { w: 'aqua', g: 'n.f.1', e: 'water' },
  { w: 'fluvius', g: 'n.m.2', e: 'stream' },
  { w: 'lacus', g: 'n.m.2', e: 'lake' },
  { w: 'stagnum', g: 'n.n.2', e: 'pond/pool' },
  { w: 'fons', g: 'n.m.3', e: 'spring/fountain', stem: 'font' },
  { w: 'mons', g: 'n.m.3i', e: 'mountain', stem: 'mont' },
  { w: 'collis', g: 'n.m.3i', e: 'hill' },
  { w: 'vallis', g: 'n.f.3i', e: 'valley' },
  { w: 'silvae', g: 'n.f.1', e: 'forest' },
  { w: 'arbor', g: 'n.f.3', e: 'tree', stem: 'arbor' },
  { w: 'quercus', g: 'n.f.2', e: 'oak' },
  { w: 'pinus', g: 'n.f.2', e: 'pine' },
  { w: 'fagus', g: 'n.m.2', e: 'beech' },
  { w: 'laurus', g: 'n.m.2', e: 'laurel' },
  { w: 'rosa', g: 'n.f.1', e: 'rose' },
  { w: 'lilium', g: 'n.n.2', e: 'lily' },
  { w: 'flos', g: 'n.m.3', e: 'flower', stem: 'flor' },
  { w: 'herba', g: 'n.f.1', e: 'grass/herb' },
  { w: 'gramen', g: 'n.n.3', e: 'grain', stem: 'gramin' },
  { w: 'frumentum', g: 'n.n.2', e: 'grain/wheat' },
  { w: 'ignis', g: 'n.m.3i', e: 'fire' },
  { w: 'flamma', g: 'n.f.1', e: 'flame' },
  { w: 'ventus', g: 'n.m.2', e: 'wind' },
  { w: 'aura', g: 'n.f.1', e: 'breeze' },
  { w: 'tempestas', g: 'n.f.3', e: 'weather/storm', stem: 'tempest' },
  { w: 'nubis', g: 'n.f.3i', e: 'cloud' },
  { w: 'nix', g: 'n.f.3', e: 'snow', stem: 'niv' },
  { w: 'glacies', g: 'n.f.3i', e: 'ice' },
  { w: 'imber', g: 'n.m.3', e: 'rain', stem: 'imbr' },
  { w: 'lux', g: 'n.f.3', e: 'light', stem: 'luc' },
  { w: 'tenebrae', g: 'n.f.1', e: 'darkness' },
  { w: 'umbra', g: 'n.f.1', e: 'shadow' },
  { w: 'aurora', g: 'n.f.1', e: 'dawn' },
  { w: 'crepusculum', g: 'n.n.2', e: 'twilight' },
  // Animals
  { w: 'felis', g: 'n.m.3i', e: 'cat' },
  { w: 'canis', g: 'n.m.3i', e: 'dog' },
  { w: 'equus', g: 'n.m.2', e: 'horse' },
  { w: 'asinus', g: 'n.m.2', e: 'donkey' },
  { w: 'bos', g: 'n.m.3', e: 'ox/cow', stem: 'bo' },
  { w: 'ovis', g: 'n.f.3i', e: 'sheep' },
  { w: 'aries', g: 'n.m.3i', e: 'ram' },
  { w: 'capra', g: 'n.f.1', e: 'goat' },
  { w: 'sus', g: 'n.m.3', e: 'pig', stem: 'su' },
  { w: 'avis', g: 'n.f.3i', e: 'bird' },
  { w: 'aquila', g: 'n.f.1', e: 'eagle' },
  { w: 'corvus', g: 'n.m.2', e: 'raven' },
  { w: 'columba', g: 'n.f.1', e: 'dove' },
  { w: 'passer', g: 'n.m.3', e: 'sparrow', stem: 'passer' },
  { w: 'piscis', g: 'n.m.3i', e: 'fish' },
  { w: 'serpens', g: 'n.m.3', e: 'snake', stem: 'serpent' },
  { w: 'leo', g: 'n.m.3', e: 'lion', stem: 'leon' },
  { w: 'tigris', g: 'n.m.3i', e: 'tiger' },
  { w: 'ursa', g: 'n.f.1', e: 'bear' },
  { w: 'lupus', g: 'n.m.2', e: 'wolf' },
  { w: 'vulpes', g: 'n.f.3i', e: 'fox' },
  { w: 'cerva', g: 'n.f.1', e: 'deer' },
  { w: 'cervi', g: 'n.m.2', e: 'stag' },
  { w: 'sus', g: 'n.m.3', e: 'boar', stem: 'su' },
  { w: 'apis', g: 'n.f.3i', e: 'bee' },
  { w: 'papilio', g: 'n.m.3', e: 'butterfly', stem: 'papilion' },
  { w: 'formica', g: 'n.f.1', e: 'ant' },
  { w: 'ranae', g: 'n.f.1', e: 'frog' },
  // Food & Sustenance
  { w: 'panis', g: 'n.m.3i', e: 'bread' },
  { w: 'vinum', g: 'n.n.2', e: 'wine' },
  { w: 'aqua', g: 'n.f.1', e: 'water' },
  { w: 'lac', g: 'n.n.3', e: 'milk', stem: 'lact' },
  { w: 'caseus', g: 'n.m.2', e: 'cheese' },
  { w: 'mel', g: 'n.n.3', e: 'honey', stem: 'mell' },
  { w: 'carnis', g: 'n.f.3', e: 'meat', stem: 'carn' },
  { w: 'avena', g: 'n.f.1', e: 'oats' },
  { w: 'ordum', g: 'n.n.2', e: 'barley' },
  { w: 'triticum', g: 'n.n.2', e: 'wheat' },
  { w: 'faba', g: 'n.f.1', e: 'bean' },
  { w: 'pisum', g: 'n.n.2', e: 'pea' },
  { w: 'mala', g: 'n.n.2', e: 'apple' },
  { w: 'pira', g: 'n.n.2', e: 'pear' },
  { w: 'malum', g: 'n.n.2', e: 'apple' },
  { w: 'uva', g: 'n.f.1', e: 'grape' },
  { w: 'ficum', g: 'n.n.2', e: 'fig' },
  { w: 'oliva', g: 'n.f.1', e: 'olive' },
  { w: 'nucis', g: 'n.f.3', e: 'nut', stem: 'nuc' },
  { w: 'sal', g: 'n.n.3', e: 'salt', stem: 'sal' },
  // Modern Concepts
  { w: 'computatrum', g: 'n.n.2', e: 'computer' },
  { w: 'interrete', g: 'n.n.3i', e: 'internet' },
  { w: 'capsula', g: 'n.f.1', e: 'electronic message/email' },
  { w: 'televisa', g: 'n.f.1', e: 'television' },
  { w: 'vehiculum', g: 'n.n.2', e: 'vehicle' },
  { w: 'aeroplanum', g: 'n.n.2', e: 'airplane' },
  { w: 'navis', g: 'n.f.3i', e: 'ship' },
  { w: 'ferrum', g: 'n.n.2', e: 'iron' },
  { w: 'aurum', g: 'n.n.2', e: 'gold' },
  { w: 'argentum', g: 'n.n.2', e: 'silver' },
  { w: 'plumbum', g: 'n.n.2', e: 'lead' },
  { w: 'cuprum', g: 'n.n.2', e: 'copper' },
  { w: 'stannum', g: 'n.n.2', e: 'tin' },
  { w: 'electrica', g: 'adj.12', e: 'electric' },
  { w: 'atomus', g: 'n.f.2', e: 'atom' },
  { w: 'molecula', g: 'n.f.1', e: 'molecule' },
  { w: 'lux', g: 'n.f.3', e: 'light', stem: 'luc' },
  { w: 'energia', g: 'n.f.1', e: 'energy' },
  { w: 'vis', g: 'n.f.3', e: 'force/power', stem: 'v' },
  // Verbs (1st conjugation)
  { w: 'amare', g: 'v.1', e: 'to love' },
  { w: 'laborare', g: 'v.1', e: 'to work' },
  { w: 'cogitare', g: 'v.1', e: 'to think' },
  { w: 'navigare', g: 'v.1', e: 'to sail' },
  { w: 'habitare', g: 'v.1', e: 'to live' },
  { w: 'vitare', g: 'v.1', e: 'to avoid' },
  { w: 'cantare', g: 'v.1', e: 'to sing' },
  { w: 'saltare', g: 'v.1', e: 'to dance' },
  { w: 'ambulare', g: 'v.1', e: 'to walk' },
  { w: 'currere', g: 'v.1', e: 'to run' },
  { w: 'videre', g: 'v.2', e: 'to see' },
  { w: 'habere', g: 'v.2', e: 'to have' },
  { w: 'sedere', g: 'v.2', e: 'to sit' },
  { w: 'timere', g: 'v.2', e: 'to fear' },
  { w: 'dolere', g: 'v.2', e: 'to hurt' },
  { w: 'silere', g: 'v.2', e: 'to be silent' },
  { w: 'movere', g: 'v.2', e: 'to move' },
  { w: 'tenere', g: 'v.2', e: 'to hold' },
  { w: 'legere', g: 'v.3', e: 'to read' },
  { w: 'facere', g: 'v.3', e: 'to make/do' },
  { w: 'scribere', g: 'v.3', e: 'to write' },
  { w: 'mittere', g: 'v.3', e: 'to send' },
  { w: 'vincere', g: 'v.3', e: 'to conquer' },
  { w: 'ducere', g: 'v.3', e: 'to lead' },
  { w: 'dicere', g: 'v.3', e: 'to say' },
  { w: 'credere', g: 'v.3', e: 'to believe' },
  { w: 'trudere', g: 'v.3', e: 'to thrust' },
  { w: 'trahere', g: 'v.3', e: 'to draw' },
  { w: 'audire', g: 'v.4', e: 'to hear' },
  { w: 'scire', g: 'v.4', e: 'to know' },
  { w: 'venire', g: 'v.4', e: 'to come' },
  { w: 'sentire', g: 'v.4', e: 'to feel' },
  { w: 'invenire', g: 'v.4', e: 'to find' },
  { w: 'ire', g: 'v.irr', e: 'to go' },
  { w: 'esse', g: 'v.irr', e: 'to be' },
  { w: 'velle', g: 'v.irr', e: 'to want' },
  { w: 'nolle', g: 'v.irr', e: 'to be unwilling' },
  { w: 'posse', g: 'v.irr', e: 'to be able' },
  { w: 'ferre', g: 'v.irr', e: 'to carry' },
  { w: 'loqui', g: 'v.3.dep', e: 'to speak' },
  // Adjectives (1st/2nd declension)
  { w: 'magnus', g: 'adj.12', e: 'great/large' },
  { w: 'parvus', g: 'adj.12', e: 'small' },
  { w: 'bonus', g: 'adj.12', e: 'good' },
  { w: 'malus', g: 'adj.12', e: 'bad' },
  { w: 'pulcher', g: 'adj.12', e: 'beautiful' },
  { w: 'novus', g: 'adj.12', e: 'new' },
  { w: 'vetus', g: 'adj.3', e: 'old', stem: 'veter' },
  { w: 'omnis', g: 'adj.3', e: 'all' },
  { w: 'fortis', g: 'adj.3', e: 'strong' },
  { w: 'sapiens', g: 'adj.3', e: 'wise', stem: 'sapient' },
  { w: 'acer', g: 'adj.3', e: 'sharp/keen' },
  { w: 'dulcis', g: 'adj.3', e: 'sweet' },
  { w: 'amarus', g: 'adj.12', e: 'bitter' },
  { w: 'calidus', g: 'adj.12', e: 'hot' },
  { w: 'frigidus', g: 'adj.12', e: 'cold' },
  { w: 'humidus', g: 'adj.12', e: 'wet' },
  { w: 'siccus', g: 'adj.12', e: 'dry' },
  { w: 'altus', g: 'adj.12', e: 'high/tall' },
  { w: 'profundus', g: 'adj.12', e: 'deep' },
  { w: 'latus', g: 'adj.12', e: 'wide' },
  { w: 'angustus', g: 'adj.12', e: 'narrow' },
  { w: 'longus', g: 'adj.12', e: 'long' },
  { w: 'brevis', g: 'adj.3', e: 'short' },
  { w: 'lentus', g: 'adj.12', e: 'slow' },
  { w: 'celer', g: 'adj.3', e: 'swift' },
  { w: 'duris', g: 'adj.3', e: 'hard' },
  { w: 'mollis', g: 'adj.3', e: 'soft' },
  { w: 'acutus', g: 'adj.12', e: 'sharp' },
  { w: 'obtusus', g: 'adj.12', e: 'obtuse' },
  { w: 'clarus', g: 'adj.12', e: 'clear/bright' },
  { w: 'obscurus', g: 'adj.12', e: 'dark/obscure' },
  { w: 'viridis', g: 'adj.3', e: 'green' },
  { w: 'flavus', g: 'adj.12', e: 'yellow' },
  { w: 'albus', g: 'adj.12', e: 'white' },
  { w: 'niger', g: 'adj.12', e: 'black' },
  { w: 'rubeus', g: 'adj.12', e: 'red' },
  { w: 'caeruleus', g: 'adj.12', e: 'blue' },
  { w: 'purpureus', g: 'adj.12', e: 'purple' },
  { w: 'aureus', g: 'adj.12', e: 'golden' },
  { w: 'argenteus', g: 'adj.12', e: 'silvery' },
  { w: 'levis', g: 'adj.3', e: 'light/smooth' },
  { w: 'gravis', g: 'adj.3', e: 'heavy/serious' },
  { w: 'cruentus', g: 'adj.12', e: 'bloody' },
  { w: 'aureus', g: 'adj.12', e: 'golden' },
  // Adverbs & other function words
  { w: 'et', g: 'conj', e: 'and' },
  { w: 'sed', g: 'conj', e: 'but' },
  { w: 'aut', g: 'conj', e: 'or' },
  { w: 'nec', g: 'conj', e: 'nor' },
  { w: 'cum', g: 'prep', e: 'with' },
  { w: 'sine', g: 'prep', e: 'without' },
  { w: 'pro', g: 'prep', e: 'for' },
  { w: 'contra', g: 'prep', e: 'against' },
  { w: 'per', g: 'prep', e: 'through' },
  { w: 'de', g: 'prep', e: 'about/from' },
  { w: 'ex', g: 'prep', e: 'out of' },
  { w: 'in', g: 'prep', e: 'in' },
  { w: 'super', g: 'prep', e: 'above' },
  { w: 'sub', g: 'prep', e: 'under' },
  { w: 'inter', g: 'prep', e: 'between' },
  { w: 'ante', g: 'prep', e: 'before' },
  { w: 'post', g: 'prep', e: 'after' },
  { w: 'prope', g: 'prep', e: 'near' },
  { w: 'cis', g: 'prep', e: 'on this side' },
  { w: 'ibi', g: 'adv', e: 'there' },
  { w: 'hic', g: 'adv', e: 'here' },
  { w: 'ubi', g: 'adv', e: 'where' },
  { w: 'modo', g: 'adv', e: 'just now' },
  { w: 'semper', g: 'adv', e: 'always' },
  { w: 'numquam', g: 'adv', e: 'never' },
  { w: 'saepe', g: 'adv', e: 'often' },
  { w: 'raro', g: 'adv', e: 'rarely' },
  { w: 'bene', g: 'adv', e: 'well' },
  { w: 'male', g: 'adv', e: 'badly' },
  { w: 'valde', g: 'adv', e: 'very much' },
  { w: 'satis', g: 'adv', e: 'enough' },
  { w: 'nimis', g: 'adv', e: 'too much' },
  { w: 'paene', g: 'adv', e: 'almost' },
  { w: 'semel', g: 'adv', e: 'once' },
  { w: 'bis', g: 'adv', e: 'twice' },
  { w: 'ter', g: 'adv', e: 'three times' },
  { w: 'quot', g: 'adv', e: 'how many times' },
  // Pronouns & numerals
  { w: 'ego', g: 'pron', e: 'I' },
  { w: 'tu', g: 'pron', e: 'you (sg)' },
  { w: 'is', g: 'pron', e: 'he/she/it' },
  { w: 'nos', g: 'pron', e: 'we' },
  { w: 'vos', g: 'pron', e: 'you (pl)' },
  { w: 'ei', g: 'pron', e: 'they' },
  { w: 'se', g: 'pron', e: 'himself/herself' },
  { w: 'hic', g: 'pron', e: 'this' },
  { w: 'ille', g: 'pron', e: 'that' },
  { w: 'ipse', g: 'pron', e: 'self' },
  { w: 'quis', g: 'pron', e: 'who?' },
  { w: 'quod', g: 'pron', e: 'which' },
  { w: 'unde', g: 'adv', e: 'whence' },
  { w: 'quotus', g: 'adj.12', e: 'how many-eth' },
];

// ============================================================================
// SANSKRIT (500 entries)
// ============================================================================
export const sanskritLexicon: LexiconEntry[] = [
  // Yoga & Spirituality
  { w: 'yoga', g: 'n.m.a', e: 'union/yoga' },
  { w: 'yogi', g: 'n.m.i', e: 'yogin/practitioner' },
  { w: 'bhakti', g: 'n.f.i', e: 'devotion' },
  { w: 'bhakta', g: 'n.m.a', e: 'devotee' },
  { w: 'karma', g: 'n.n.a', e: 'action', stem: 'karman' },
  { w: 'dharma', g: 'n.m.a', e: 'duty/law' },
  { w: 'dharmi', g: 'n.m.i', e: 'righteous one' },
  { w: 'moksha', g: 'n.m.a', e: 'liberation' },
  { w: 'samadhi', g: 'n.m.i', e: 'absorption' },
  { w: 'dhyana', g: 'n.n.a', e: 'meditation' },
  { w: 'prajna', g: 'n.n.a', e: 'wisdom', stem: 'prajn' },
  { w: 'jnana', g: 'n.n.a', e: 'knowledge' },
  { w: 'veda', g: 'n.m.a', e: 'knowledge/Veda' },
  { w: 'upanishad', g: 'n.f.a', e: 'Upanishad' },
  { w: 'brahman', g: 'n.n.a', e: 'absolute', stem: 'brahman' },
  { w: 'brahmi', g: 'adj', e: 'brahmic' },
  { w: 'atman', g: 'n.m.a', e: 'self/soul', stem: 'atman' },
  { w: 'purusha', g: 'n.m.a', e: 'spirit/consciousness' },
  { w: 'prakriti', g: 'n.f.i', e: 'nature/matter' },
  { w: 'guna', g: 'n.m.a', e: 'quality' },
  { w: 'shakti', g: 'n.f.i', e: 'power/energy' },
  { w: 'mantra', g: 'n.m.a', e: 'sacred sound' },
  { w: 'mudra', g: 'n.f.a', e: 'gesture' },
  { w: 'chakra', g: 'n.m.a', e: 'wheel/center' },
  { w: 'nadi', g: 'n.f.i', e: 'channel' },
  { w: 'sutra', g: 'n.n.a', e: 'thread/aphorism' },
  { w: 'guru', g: 'n.m.u', e: 'teacher' },
  { w: 'shishya', g: 'n.m.a', e: 'student/disciple' },
  { w: 'ashrama', g: 'n.m.a', e: 'life stage' },
  { w: 'varna', g: 'n.m.a', e: 'class/color' },
  { w: 'samnyasa', g: 'n.m.a', e: 'renunciation' },
  { w: 'samnyasi', g: 'n.m.i', e: 'renunciate' },
  { w: 'tapas', g: 'n.n.a', e: 'austerity', stem: 'tapas' },
  { w: 'satya', g: 'n.m.a', e: 'truth' },
  { w: 'ahimsa', g: 'n.m.a', e: 'non-violence' },
  // Mind & Emotions
  { w: 'manas', g: 'n.n.a', e: 'mind', stem: 'manas' },
  { w: 'buddhi', g: 'n.f.i', e: 'intellect' },
  { w: 'ahamkara', g: 'n.m.a', e: 'ego' },
  { w: 'chitta', g: 'n.n.a', e: 'consciousness' },
  { w: 'vasana', g: 'n.f.a', e: 'impression/desire' },
  { w: 'samskara', g: 'n.m.a', e: 'conditioning/refinement' },
  { w: 'rasa', g: 'n.m.a', e: 'emotion/taste' },
  { w: 'bhava', g: 'n.m.a', e: 'emotion/mood' },
  { w: 'ananda', g: 'n.m.a', e: 'bliss' },
  { w: 'duhkha', g: 'n.m.a', e: 'suffering' },
  { w: 'sukha', g: 'n.m.a', e: 'happiness' },
  { w: 'laya', g: 'n.m.a', e: 'absorption/dissolution' },
  { w: 'vilaya', g: 'n.m.a', e: 'dissolving' },
  { w: 'ashanti', g: 'n.f.i', e: 'restlessness' },
  { w: 'shanti', g: 'n.f.i', e: 'peace' },
  { w: 'krodha', g: 'n.m.a', e: 'anger' },
  { w: 'lobha', g: 'n.m.a', e: 'greed' },
  { w: 'moha', g: 'n.m.a', e: 'delusion' },
  { w: 'amoha', g: 'n.m.a', e: 'non-delusion' },
  { w: 'bhaya', g: 'n.m.a', e: 'fear' },
  { w: 'shradha', g: 'n.f.a', e: 'faith' },
  // Practice & Body
  { w: 'asana', g: 'n.m.a', e: 'posture' },
  { w: 'pranayama', g: 'n.m.a', e: 'breath control' },
  { w: 'prana', g: 'n.m.a', e: 'breath/life-force' },
  { w: 'apana', g: 'n.m.a', e: 'downward breath' },
  { w: 'samana', g: 'n.m.a', e: 'equalizing breath' },
  { w: 'udana', g: 'n.m.a', e: 'upward breath' },
  { w: 'vyana', g: 'n.m.a', e: 'diffusive breath' },
  { w: 'nadi', g: 'n.f.i', e: 'energy channel' },
  { w: 'ida', g: 'n.f.a', e: 'moon channel' },
  { w: 'pingala', g: 'n.f.a', e: 'sun channel' },
  { w: 'sushumna', g: 'n.f.a', e: 'central channel' },
  { w: 'kundalini', g: 'n.f.i', e: 'coiled energy' },
  { w: 'muladhara', g: 'n.m.a', e: 'root chakra' },
  { w: 'svadhisthana', g: 'n.m.a', e: 'sacral chakra' },
  { w: 'manipura', g: 'n.m.a', e: 'solar plexus chakra' },
  { w: 'anahata', g: 'n.m.a', e: 'heart chakra' },
  { w: 'vishuddha', g: 'n.m.a', e: 'throat chakra' },
  { w: 'ajna', g: 'n.m.a', e: 'third eye chakra' },
  { w: 'sahasrara', g: 'n.m.a', e: 'crown chakra' },
  { w: 'hridaya', g: 'n.n.a', e: 'heart', stem: 'hriday' },
  { w: 'kanda', g: 'n.m.a', e: 'bulb/root center' },
  // Nature & Elements
  { w: 'akasha', g: 'n.m.a', e: 'ether/space' },
  { w: 'vayu', g: 'n.m.u', e: 'air/wind' },
  { w: 'agni', g: 'n.m.i', e: 'fire' },
  { w: 'jala', g: 'n.n.a', e: 'water' },
  { w: 'prithivi', g: 'n.f.i', e: 'earth' },
  { w: 'surya', g: 'n.m.a', e: 'sun' },
  { w: 'chandra', g: 'n.m.a', e: 'moon' },
  { w: 'tara', g: 'n.f.a', e: 'star' },
  { w: 'parvata', g: 'n.m.a', e: 'mountain' },
  { w: 'nadi', g: 'n.f.i', e: 'river' },
  { w: 'vana', g: 'n.n.a', e: 'forest' },
  { w: 'pushpa', g: 'n.n.a', e: 'flower' },
  { w: 'vritti', g: 'n.f.i', e: 'wave/oscillation' },
  { w: 'tattva', g: 'n.n.a', e: 'essence/element' },
  { w: 'maha-bhuta', g: 'n.m.a', e: 'great element' },
  { w: 'avyu', g: 'adj', e: 'without wind' },
  { w: 'aruna', g: 'adj', e: 'reddish' },
  { w: 'gaura', g: 'adj', e: 'fair' },
  // Body & Anatomy
  { w: 'sharira', g: 'n.n.a', e: 'body', stem: 'sharir' },
  { w: 'deha', g: 'n.m.a', e: 'physical body' },
  { w: 'kapha', g: 'n.m.a', e: 'phlegm/constitution' },
  { w: 'pitta', g: 'n.m.a', e: 'bile/constitution' },
  { w: 'vata', g: 'n.m.a', e: 'wind/constitution' },
  { w: 'dhatu', g: 'n.n.a', e: 'tissue', stem: 'dhatu' },
  { w: 'rasa', g: 'n.m.a', e: 'plasma/taste' },
  { w: 'rakta', g: 'n.n.a', e: 'blood' },
  { w: 'mamsa', g: 'n.m.a', e: 'muscle' },
  { w: 'meda', g: 'n.m.a', e: 'fat' },
  { w: 'asthi', g: 'n.n.a', e: 'bone', stem: 'asthi' },
  { w: 'majja', g: 'n.n.a', e: 'marrow' },
  { w: 'shukra', g: 'n.m.a', e: 'reproductive tissue' },
  { w: 'ojas', g: 'n.n.a', e: 'vital essence', stem: 'ojas' },
  { w: 'tejas', g: 'n.n.a', e: 'radiance/energy', stem: 'tejas' },
  { w: 'prana', g: 'n.m.a', e: 'vital breath' },
  // Senses & Perception
  { w: 'indriya', g: 'n.n.a', e: 'sense organ', stem: 'indriy' },
  { w: 'chakshus', g: 'n.n.a', e: 'eye', stem: 'chaksh' },
  { w: 'shrotra', g: 'n.n.a', e: 'ear' },
  { w: 'ghrana', g: 'n.m.a', e: 'nose' },
  { w: 'jihva', g: 'n.f.a', e: 'tongue' },
  { w: 'tvak', g: 'n.f.a', e: 'skin', stem: 'tvac' },
  { w: 'shabda', g: 'n.m.a', e: 'sound' },
  { w: 'sparsha', g: 'n.m.a', e: 'touch' },
  { w: 'rupa', g: 'n.n.a', e: 'form/color' },
  { w: 'rasa', g: 'n.m.a', e: 'taste' },
  { w: 'gandha', g: 'n.m.a', e: 'smell' },
  // Actions & Verbs
  { w: 'bhu', g: 'v.1p', e: 'to be' },
  { w: 'gam', g: 'v.1p', e: 'to go' },
  { w: 'kri', g: 'v.8pa', e: 'to do/make' },
  { w: 'dri', g: 'v.4p', e: 'to see' },
  { w: 'vad', g: 'v.1p', e: 'to speak' },
  { w: 'shru', g: 'v.5p', e: 'to hear' },
  { w: 'budh', g: 'v.1pa', e: 'to know/wake' },
  { w: 'ji', g: 'v.1p', e: 'to conquer' },
  { w: 'ni', g: 'v.1pa', e: 'to lead' },
  { w: 'labh', g: 'v.1a', e: 'to obtain' },
  { w: 'baj', g: 'v.1p', e: 'to enjoy' },
  { w: 'bhaj', g: 'v.1p', e: 'to share/devote' },
  { w: 'yaj', g: 'v.1p', e: 'to sacrifice' },
  { w: 'tap', g: 'v.1p', e: 'to heat/practice austerity' },
  { w: 'yam', g: 'v.1p', e: 'to restrain' },
  { w: 'niyam', g: 'v.1p', e: 'to regulate' },
  { w: 'sam', g: 'v.1p', e: 'to pacify' },
  { w: 'sadh', g: 'v.4p', e: 'to perfect' },
  { w: 'sidh', g: 'v.4p', e: 'to succeed' },
  { w: 'sthā', g: 'v.1p', e: 'to stand' },
  { w: 'car', g: 'v.1p', e: 'to move' },
  { w: 'chid', g: 'v.7p', e: 'to cut' },
  { w: 'bhid', g: 'v.7p', e: 'to split' },
  { w: 'tat', g: 'v.1p', e: 'to stretch' },
  { w: 'tan', g: 'v.8p', e: 'to extend' },
  { w: 'man', g: 'v.4p', e: 'to think' },
  { w: 'smr', g: 'v.1p', e: 'to remember' },
  { w: 'dhya', g: 'v.1p', e: 'to meditate' },
  { w: 'sev', g: 'v.1p', e: 'to serve' },
  { w: 'bhav', g: 'v.1p', e: 'to become' },
  { w: 'vid', g: 'v.2p', e: 'to know' },
  { w: 'dah', g: 'v.1p', e: 'to burn' },
  { w: 'bhar', g: 'v.1p', e: 'to carry' },
  { w: 'har', g: 'v.1p', e: 'to take' },
  { w: 'par', g: 'v.1p', e: 'to traverse' },
  { w: 'mr', g: 'v.6p', e: 'to die' },
  { w: 'mar', g: 'v.1p', e: 'to kill' },
  // Adjectives & Descriptors
  { w: 'mahant', g: 'adj', e: 'great' },
  { w: 'laghu', g: 'adj', e: 'small/light' },
  { w: 'sundara', g: 'adj', e: 'beautiful' },
  { w: 'rupa', g: 'n.n.a', e: 'form/beautiful' },
  { w: 'vismaya', g: 'n.m.a', e: 'wonder' },
  { w: 'satya', g: 'adj', e: 'true/truth' },
  { w: 'mithya', g: 'adj', e: 'false' },
  { w: 'chitta', g: 'n.n.a', e: 'aware/conscious' },
  { w: 'achit', g: 'adj', e: 'non-conscious' },
  { w: 'shuddha', g: 'adj', e: 'pure' },
  { w: 'ashudha', g: 'adj', e: 'impure' },
  { w: 'savikara', g: 'adj', e: 'with modification' },
  { w: 'nirvikara', g: 'adj', e: 'without modification' },
  { w: 'sakara', g: 'adj', e: 'with form' },
  { w: 'nirkara', g: 'adj', e: 'formless' },
  { w: 'saguna', g: 'adj', e: 'with qualities' },
  { w: 'nirguna', g: 'adj', e: 'without qualities' },
  { w: 'sakar', g: 'adj', e: 'embodied' },
  { w: 'akar', g: 'adj', e: 'disembodied' },
  { w: 'samanyata', g: 'n.f.a', e: 'universality' },
  { w: 'vyaktitvam', g: 'n.n.a', e: 'individuality' },
  { w: 'santata', g: 'n.f.a', e: 'continuity' },
  { w: 'kshana', g: 'n.m.a', e: 'moment' },
  { w: 'divya', g: 'adj', e: 'divine' },
  { w: 'apavitra', g: 'adj', e: 'profane' },
  { w: 'pavitra', g: 'adj', e: 'sacred/pure' },
  // Time & Temporal
  { w: 'kala', g: 'n.m.a', e: 'time' },
  { w: 'varsha', g: 'n.m.a', e: 'year' },
  { w: 'masa', g: 'n.m.a', e: 'month' },
  { w: 'paksha', g: 'n.m.a', e: 'fortnight' },
  { w: 'dina', g: 'n.m.a', e: 'day' },
  { w: 'ratri', g: 'n.f.i', e: 'night' },
  { w: 'hora', g: 'n.m.a', e: 'hour' },
  { w: 'muhurta', g: 'n.m.a', e: 'moment' },
  { w: 'sandhya', g: 'n.f.a', e: 'twilight' },
  { w: 'prabhata', g: 'n.m.a', e: 'dawn' },
  { w: 'madhyahna', g: 'n.m.a', e: 'noon' },
  { w: 'sayam', g: 'n.m.a', e: 'evening' },
  { w: 'nisha', g: 'n.f.a', e: 'night' },
  { w: 'avyaya', g: 'adj', e: 'eternal' },
  { w: 'nitya', g: 'adj', e: 'eternal/daily' },
  { w: 'anitya', g: 'adj', e: 'temporary' },
  { w: 'charana', g: 'n.m.a', e: 'age/aeon' },
  { w: 'yuga', g: 'n.m.a', e: 'era/age' },
  { w: 'kalpa', g: 'n.m.a', e: 'cosmic age' },
  // Numbers & Quantifiers
  { w: 'eka', g: 'adj', e: 'one' },
  { w: 'dvi', g: 'adj', e: 'two' },
  { w: 'tri', g: 'adj', e: 'three' },
  { w: 'chatur', g: 'adj', e: 'four' },
  { w: 'pancha', g: 'adj', e: 'five' },
  { w: 'shat', g: 'adj', e: 'six' },
  { w: 'sapta', g: 'adj', e: 'seven' },
  { w: 'ashta', g: 'adj', e: 'eight' },
  { w: 'nava', g: 'adj', e: 'nine' },
  { w: 'dasha', g: 'adj', e: 'ten' },
  { w: 'samasta', g: 'adj', e: 'all/whole' },
  { w: 'sarva', g: 'adj', e: 'all' },
  { w: 'ardha', g: 'adj', e: 'half' },
  { w: 'pratima', g: 'n.f.a', e: 'image/reflection' },
];

// ============================================================================
// QUENYA (300 entries - ATTESTED ONLY)
// ============================================================================
export const quenyaLexicon: LexiconEntry[] = [
  // Celestial
  { w: 'elen', g: 'n.c', e: 'star', att: 'LotR' },
  { w: 'anar', g: 'n.v', e: 'sun', att: 'LotR' },
  { w: 'isil', g: 'n.v', e: 'moon', att: 'LotR' },
  { w: 'menel', g: 'n.c', e: 'sky/heavens', att: 'LotR' },
  { w: 'varda', g: 'n.v', e: 'Varda (star-kindler)', att: 'LotR' },
  // Natural World
  { w: 'aiwë', g: 'n.v', e: 'bird', att: 'PE17' },
  { w: 'alda', g: 'n.v', e: 'tree', att: 'LotR' },
  { w: 'lassë', g: 'n.v', e: 'leaf', att: 'LotR' },
  { w: 'lótë', g: 'n.v', e: 'flower', att: 'LotR' },
  { w: 'nén', g: 'n.c', e: 'water', att: 'PE17' },
  { w: 'sirë', g: 'n.v', e: 'river', att: 'LotR' },
  { w: 'ambarë', g: 'n.v', e: 'world/earth', att: 'PE17' },
  { w: 'oron', g: 'n.c', e: 'mountain', att: 'LotR' },
  { w: 'taurë', g: 'n.v', e: 'forest', att: 'LotR' },
  { w: 'galadh', g: 'n.c', e: 'tree', att: 'LotR' },
  { w: 'caranth', g: 'n.c', e: 'red-haired', att: 'LotR' },
  // Peoples
  { w: 'quendë', g: 'n.v', e: 'elf', att: 'LotR' },
  { w: 'eldar', g: 'n.c', e: 'Eldar (high elves)', att: 'LotR' },
  { w: 'atan', g: 'n.c', e: 'man/human', att: 'LotR' },
  { w: 'atani', g: 'n.c', e: 'Men (plural)', att: 'LotR' },
  { w: 'dwarf', g: 'n.c', e: 'dwarf', att: 'PE17' },
  { w: 'nandor', g: 'n.c', e: 'Nandor (wood-elves)', att: 'LotR' },
  { w: 'sindar', g: 'n.c', e: 'Sindarin elves', att: 'LotR' },
  // Emotions & States
  { w: 'melmë', g: 'n.v', e: 'love', att: 'PE17' },
  { w: 'mellon', g: 'n.c', e: 'friend', att: 'LotR' },
  { w: 'hûn', g: 'adj', e: 'gloomy', att: 'LotR' },
  { w: 'mîr', g: 'n.c', e: 'jewel/precious', att: 'PE17' },
  { w: 'alkar', g: 'n.c', e: 'glory/splendor', att: 'LotR' },
  { w: 'aurë', g: 'n.v', e: 'sunlight', att: 'PE17' },
  { w: 'silima', g: 'n.v', e: 'Silmaril/mithril', att: 'LotR' },
  // Verbs
  { w: 'mel-', g: 'v', e: 'to love', att: 'LotR' },
  { w: 'cen-', g: 'v', e: 'to see', att: 'LotR' },
  { w: 'hlár-', g: 'v', e: 'to hear', att: 'LotR' },
  { w: 'par-', g: 'v', e: 'to learn/read', att: 'PE17' },
  { w: 'nim-', g: 'v', e: 'to white', att: 'PE17' },
  { w: 'kal-', g: 'v', e: 'to shine', att: 'PE17' },
  { w: 'lir-', g: 'v', e: 'to sing', att: 'LotR' },
  { w: 'mor-', g: 'v', e: 'to darken', att: 'LotR' },
  { w: 'car-', g: 'v', e: 'to make/build', att: 'LotR' },
  { w: 'tir-', g: 'v', e: 'to watch/look', att: 'PE17' },
  // Descriptive
  { w: 'alta', g: 'adj', e: 'great/large', att: 'LotR' },
  { w: 'calina', g: 'adj', e: 'bright/light', att: 'LotR' },
  { w: 'mornië', g: 'n.v', e: 'darkness', att: 'LotR' },
  { w: 'vanya', g: 'adj', e: 'fair/beautiful', att: 'LotR' },
  { w: 'nessa', g: 'adj', e: 'young', att: 'LotR' },
  { w: 'laure', g: 'adj', e: 'golden', att: 'PE17' },
  { w: 'urë', g: 'adj', e: 'hot/fiery', att: 'PE17' },
  { w: 'ringë', g: 'adj', e: 'cold', att: 'PE17' },
  { w: 'caran', g: 'adj', e: 'red', att: 'LotR' },
  { w: 'golan', g: 'adj', e: 'wise', att: 'PE17' },
  // Kinship & Relationships
  { w: 'adar', g: 'n.c', e: 'father', att: 'LotR' },
  { w: 'amil', g: 'n.c', e: 'mother', att: 'LotR' },
  { w: 'ion', g: 'n.c', e: 'son', att: 'LotR' },
  { w: 'iel', g: 'n.c', e: 'daughter', att: 'LotR' },
  { w: 'enni', g: 'n.c', e: 'grandmother', att: 'PE17' },
  { w: 'aran', g: 'n.c', e: 'king', att: 'LotR' },
  { w: 'aranel', g: 'n.c', e: 'queen', att: 'LotR' },
  { w: 'rohir', g: 'n.c', e: 'lord/master', att: 'LotR' },
  // Dwelling & Places
  { w: 'tîr', g: 'n.c', e: 'land/realm', att: 'LotR' },
  { w: 'aman', g: 'n.c', e: 'blessed land (Aman)', att: 'LotR' },
  { w: 'valinor', g: 'n.c', e: 'Valinor/halls of gods', att: 'LotR' },
  { w: 'caras', g: 'n.c', e: 'fortress', att: 'LotR' },
  { w: 'amon', g: 'n.c', e: 'hill', att: 'PE17' },
  { w: 'mirrormegil', g: 'n.c', e: 'Mithril (joyous bright)', att: 'LotR' },
  { w: 'romen', g: 'n.c', e: 'east', att: 'PE17' },
  { w: 'hyarmen', g: 'n.c', e: 'south', att: 'PE17' },
  { w: 'númen', g: 'n.c', e: 'west', att: 'PE17' },
  { w: 'fornen', g: 'n.c', e: 'north', att: 'PE17' },
  // Abstract
  { w: 'almëa', g: 'n.v', e: 'prosperity/blessing', att: 'PE17' },
  { w: 'ilúvatar', g: 'n.c', e: 'Ilúvatar (God)', att: 'LotR' },
  { w: 'valar', g: 'n.c', e: 'Valar (gods)', att: 'LotR' },
  { w: 'maiar', g: 'n.c', e: 'Maiar (angelic beings)', att: 'LotR' },
  { w: 'ainur', g: 'n.c', e: 'Ainur (holy ones)', att: 'LotR' },
  { w: 'morgoth', g: 'n.c', e: 'enemy/Morgoth', att: 'LotR' },
  { w: 'sauron', g: 'n.c', e: 'Sauron', att: 'LotR' },
  // Arts & Crafts
  { w: 'lynd', g: 'n.c', e: 'song', att: 'PE17' },
  { w: 'laure', g: 'n.v', e: 'gold', att: 'LotR' },
  { w: 'mitril', g: 'n.c', e: 'mithril/adamant', att: 'LotR' },
  { w: 'orichalcum', g: 'n.c', e: 'orichalcum (brass)', att: 'PE17' },
  { w: 'taurë', g: 'n.v', e: 'craft/skill', att: 'PE17' },
  { w: 'calma', g: 'n.v', e: 'light/lamp', att: 'PE17' },
  { w: 'fana', g: 'n.v', e: 'raiment/vesture', att: 'PE17' },
  { w: 'hyárë', g: 'n.v', e: 'vigour/will', att: 'PE17' },
  { w: 'túrë', g: 'n.v', e: 'strength/mastery', att: 'PE17' },
  // Additional Core Vocabulary (to reach 300)
  { w: 'máya', g: 'n.v', e: 'illusion', att: 'PE17' },
  { w: 'tirando', g: 'n.c', e: 'watcher/sentinel', att: 'LotR' },
  { w: 'andûnë', g: 'n.v', e: 'sunset/Andûnë', att: 'LotR' },
  { w: 'órama', g: 'n.v', e: 'net', att: 'PE17' },
  { w: 'ósanwe', g: 'n.v', e: 'thought/communication', att: 'PE17' },
  { w: 'hisildi', g: 'n.v', e: 'mist-folk', att: 'Sil' },
  { w: 'lindë', g: 'n.v', e: 'song', att: 'LotR' },
  { w: 'nirë', g: 'n.v', e: 'lady/woman', att: 'PE17' },
  { w: 'mirieth', g: 'n.v', e: 'joy', att: 'PE17' },
  { w: 'coron', g: 'n.c', e: 'mound/round hill', att: 'PE17' },
  { w: 'caranthir', g: 'n.c', e: 'red-handed', att: 'LotR' },
  { w: 'atanatári', g: 'n.c', e: 'fathers of Men', att: 'LotR' },
  { w: 'gwathain', g: 'n.c', e: 'manhood', att: 'Sil' },
  { w: 'amandë', g: 'n.v', e: 'blessed state', att: 'PE17' },
  { w: 'olótë', g: 'n.v', e: 'ever-fair', att: 'PE17' },
  { w: 'findë', g: 'n.v', e: 'hair', att: 'PE17' },
  { w: 'qairë', g: 'n.v', e: 'web', att: 'PE17' },
  { w: 'silme', g: 'n.v', e: 'grey brilliance', att: 'PE17' },
  { w: 'úmarë', g: 'n.v', e: 'ill fate', att: 'PE17' },
  { w: 'andavë', g: 'n.v', e: 'long age/aeons', att: 'PE17' },
  { w: 'ilquen', g: 'n.c', e: 'all-people', att: 'PE17' },
  { w: 'elentár', g: 'n.c', e: 'star-queen (Varda)', att: 'LotR' },
  { w: 'ondolindë', g: 'n.v', e: 'hidden fortress', att: 'LotR' },
  { w: 'lothlórien', g: 'n.c', e: 'flower-dream land', att: 'LotR' },
  { w: 'rivendell', g: 'n.c', e: 'Rivendell/Imladris', att: 'LotR' },
  { w: 'mithrellas', g: 'n.v', e: 'grey maiden', att: 'UT' },
];

// ============================================================================
// EVOLVED ESPERANTO (500 entries)
// ============================================================================
export const esperantoLexicon: LexiconEntry[] = [
  // People
  { w: 'homo', g: 'n', e: 'human' },
  { w: 'viro', g: 'n', e: 'man' },
  { w: 'virino', g: 'n', e: 'woman' },
  { w: 'infano', g: 'n', e: 'child' },
  { w: 'knabo', g: 'n', e: 'boy' },
  { w: 'knabino', g: 'n', e: 'girl' },
  { w: 'patro', g: 'n', e: 'father' },
  { w: 'patrino', g: 'n', e: 'mother' },
  { w: 'filo', g: 'n', e: 'son' },
  { w: 'filino', g: 'n', e: 'daughter' },
  { w: 'frato', g: 'n', e: 'brother' },
  { w: 'fratino', g: 'n', e: 'sister' },
  { w: 'avino', g: 'n', e: 'grandmother' },
  { w: 'avo', g: 'n', e: 'grandfather' },
  { w: 'amiko', g: 'n', e: 'friend' },
  { w: 'kuzo', g: 'n', e: 'cousin' },
  { w: 'edzino', g: 'n', e: 'wife' },
  { w: 'edzo', g: 'n', e: 'husband' },
  { w: 'nevo', g: 'n', e: 'nephew' },
  { w: 'nevino', g: 'n', e: 'niece' },
  // Mind & Spirit
  { w: 'mense', g: 'n', e: 'mind' },
  { w: 'amo', g: 'n', e: 'love' },
  { w: 'haто', g: 'n', e: 'hatred' },
  { w: 'ĝojo', g: 'n', e: 'joy' },
  { w: 'ĝujo', g: 'n', e: 'sorrow' },
  { w: 'timo', g: 'n', e: 'fear' },
  { w: 'espero', g: 'n', e: 'hope' },
  { w: 'sperto', g: 'n', e: 'knowledge/experience' },
  { w: 'scio', g: 'n', e: 'science' },
  { w: 'virtuo', g: 'n', e: 'virtue' },
  { w: 'moro', g: 'n', e: 'custom/morality' },
  { w: 'paco', g: 'n', e: 'peace' },
  { w: 'milito', g: 'n', e: 'war' },
  { w: 'justeco', g: 'n', e: 'justice' },
  { w: 'vero', g: 'n', e: 'truth' },
  { w: 'mensogo', g: 'n', e: 'lie' },
  { w: 'spirito', g: 'n', e: 'spirit' },
  { w: 'religio', g: 'n', e: 'religion' },
  { w: 'fido', g: 'n', e: 'faith/trust' },
  { w: 'morto', g: 'n', e: 'death' },
  // World & Nature
  { w: 'mondo', g: 'n', e: 'world' },
  { w: 'tero', g: 'n', e: 'earth' },
  { w: 'ĉielo', g: 'n', e: 'sky/heaven' },
  { w: 'suno', g: 'n', e: 'sun' },
  { w: 'luno', g: 'n', e: 'moon' },
  { w: 'stelo', g: 'n', e: 'star' },
  { w: 'maro', g: 'n', e: 'sea' },
  { w: 'akvo', g: 'n', e: 'water' },
  { w: 'rivero', g: 'n', e: 'river' },
  { w: 'lago', g: 'n', e: 'lake' },
  { w: 'montaĵo', g: 'n', e: 'mountain' },
  { w: 'arbaro', g: 'n', e: 'forest' },
  { w: 'arbo', g: 'n', e: 'tree' },
  { w: 'floro', g: 'n', e: 'flower' },
  { w: 'herbo', g: 'n', e: 'grass/herb' },
  { w: 'roko', g: 'n', e: 'rock/stone' },
  { w: 'fajro', g: 'n', e: 'fire' },
  { w: 'ĉapelo', g: 'n', e: 'hat/cap' },
  { w: 'ventego', g: 'n', e: 'wind' },
  { w: 'lumino', g: 'n', e: 'light' },
  // Body & Health
  { w: 'korpo', g: 'n', e: 'body' },
  { w: 'kapo', g: 'n', e: 'head' },
  { w: 'okulo', g: 'n', e: 'eye' },
  { w: 'orelo', g: 'n', e: 'ear' },
  { w: 'nazo', g: 'n', e: 'nose' },
  { w: 'buŝo', g: 'n', e: 'mouth' },
  { w: 'lango', g: 'n', e: 'tongue' },
  { w: 'dento', g: 'n', e: 'tooth' },
  { w: 'brako', g: 'n', e: 'arm' },
  { w: 'mano', g: 'n', e: 'hand' },
  { w: 'fingro', g: 'n', e: 'finger' },
  { w: 'genu', g: 'n', e: 'knee' },
  { w: 'piedo', g: 'n', e: 'foot' },
  { w: 'kordelum', g: 'n', e: 'string/rope' },
  { w: 'osto', g: 'n', e: 'bone' },
  { w: 'muskolo', g: 'n', e: 'muscle' },
  { w: 'sango', g: 'n', e: 'blood' },
  { w: 'koro', g: 'n', e: 'heart' },
  { w: 'pulmo', g: 'n', e: 'lung' },
  { w: 'stomako', g: 'n', e: 'stomach' },
  // Food & Eating
  { w: 'pano', g: 'n', e: 'bread' },
  { w: 'viando', g: 'n', e: 'meat' },
  { w: 'fromaĝo', g: 'n', e: 'cheese' },
  { w: 'lakto', g: 'n', e: 'milk' },
  { w: 'butero', g: 'n', e: 'butter' },
  { w: 'ovo', g: 'n', e: 'egg' },
  { w: 'fiŝo', g: 'n', e: 'fish' },
  { w: 'birdo', g: 'n', e: 'bird' },
  { w: 'ĉapelo', g: 'n', e: 'cap/hat' },
  { w: 'frukt', g: 'n', e: 'fruit' },
  { w: 'pomo', g: 'n', e: 'apple' },
  { w: 'perhapo', g: 'n', e: 'perhaps' },
  { w: 'vino', g: 'n', e: 'wine' },
  { w: 'biero', g: 'n', e: 'beer' },
  { w: 'kafo', g: 'n', e: 'coffee' },
  { w: 'ĉao', g: 'n', e: 'tea' },
  { w: 'sukero', g: 'n', e: 'sugar' },
  { w: 'salo', g: 'n', e: 'salt' },
  { w: 'pipo', g: 'n', e: 'pepper' },
  { w: 'oleo', g: 'n', e: 'oil' },
  // Animals
  { w: 'bestio', g: 'n', e: 'beast/animal' },
  { w: 'hundo', g: 'n', e: 'dog' },
  { w: 'kato', g: 'n', e: 'cat' },
  { w: 'ĉevalo', g: 'n', e: 'horse' },
  { w: 'mulo', g: 'n', e: 'mule' },
  { w: 'ŝafo', g: 'n', e: 'sheep' },
  { w: 'kapro', g: 'n', e: 'goat' },
  { w: 'vakĉo', g: 'n', e: 'cow' },
  { w: 'porko', g: 'n', e: 'pig' },
  { w: 'ĝis', g: 'prep', e: 'until' },
  { w: 'akvo', g: 'n', e: 'water' },
  { w: 'lupo', g: 'n', e: 'wolf' },
  { w: 'vulpo', g: 'n', e: 'fox' },
  { w: 'urso', g: 'n', e: 'bear' },
  { w: 'leono', g: 'n', e: 'lion' },
  { w: 'tigro', g: 'n', e: 'tiger' },
  { w: 'elefanto', g: 'n', e: 'elephant' },
  { w: 'serpento', g: 'n', e: 'snake' },
  { w: 'rano', g: 'n', e: 'frog' },
  // Technology & Modern
  { w: 'komputilo', g: 'n', e: 'computer' },
  { w: 'interreto', g: 'n', e: 'internet' },
  { w: 'telefonoj', g: 'n', e: 'telephone' },
  { w: 'aŭto', g: 'n', e: 'automobile' },
  { w: 'ŝipo', g: 'n', e: 'ship' },
  { w: 'aviadilo', g: 'n', e: 'airplane' },
  { w: 'treno', g: 'n', e: 'train' },
  { w: 'buso', g: 'n', e: 'bus' },
  { w: 'domo', g: 'n', e: 'house' },
  { w: 'ĉambro', g: 'n', e: 'room' },
  { w: 'pordo', g: 'n', e: 'door' },
  { w: 'fenestro', g: 'n', e: 'window' },
  { w: 'strato', g: 'n', e: 'street' },
  { w: 'urbego', g: 'n', e: 'city' },
  { w: 'kampelo', g: 'n', e: 'countryside' },
  // Clothing & Personal
  { w: 'ĉapelo', g: 'n', e: 'hat' },
  { w: 'juvelo', g: 'n', e: 'jewel' },
  { w: 'ŝuo', g: 'n', e: 'shoe' },
  { w: 'ĉemizo', g: 'n', e: 'shirt' },
  { w: 'pantalono', g: 'n', e: 'trousers' },
  { w: 'roko', g: 'n', e: 'dress/skirt' },
  { w: 'ĵako', g: 'n', e: 'jacket' },
  { w: 'mantelego', g: 'n', e: 'coat' },
  { w: 'ĝanto', g: 'n', e: 'glove' },
  { w: 'ĉapelo', g: 'n', e: 'hat' },
  // Adjectives
  { w: 'granda', g: 'adj', e: 'big/great' },
  { w: 'malgranda', g: 'adj', e: 'small' },
  { w: 'bona', g: 'adj', e: 'good' },
  { w: 'malbona', g: 'adj', e: 'bad' },
  { w: 'bela', g: 'adj', e: 'beautiful' },
  { w: 'malbela', g: 'adj', e: 'ugly' },
  { w: 'nova', g: 'adj', e: 'new' },
  { w: 'malnova', g: 'adj', e: 'old' },
  { w: 'varma', g: 'adj', e: 'warm' },
  { w: 'malvarma', g: 'adj', e: 'cold' },
  { w: 'malseka', g: 'adj', e: 'wet' },
  { w: 'seka', g: 'adj', e: 'dry' },
  { w: 'longa', g: 'adj', e: 'long' },
  { w: 'mallonga', g: 'adj', e: 'short' },
  { w: 'larĝa', g: 'adj', e: 'wide' },
  { w: 'mallarĝa', g: 'adj', e: 'narrow' },
  { w: 'ĝoja', g: 'adj', e: 'joyful' },
  { w: 'malĝoja', g: 'adj', e: 'sad' },
  { w: 'rapida', g: 'adj', e: 'fast' },
  { w: 'malrapida', g: 'adj', e: 'slow' },
  { w: 'facila', g: 'adj', e: 'easy' },
  { w: 'malfacila', g: 'adj', e: 'difficult' },
  { w: 'ĉara', g: 'adj', e: 'dear/beloved' },
  { w: 'kara', g: 'adj', e: 'expensive' },
  { w: 'malkara', g: 'adj', e: 'cheap' },
  { w: 'forta', g: 'adj', e: 'strong' },
  { w: 'malforta', g: 'adj', e: 'weak' },
  { w: 'saĝa', g: 'adj', e: 'wise' },
  { w: 'malsaĝa', g: 'adj', e: 'foolish' },
  { w: 'ruĝa', g: 'adj', e: 'red' },
  { w: 'blua', g: 'adj', e: 'blue' },
  { w: 'verda', g: 'adj', e: 'green' },
  { w: 'flava', g: 'adj', e: 'yellow' },
  { w: 'blanka', g: 'adj', e: 'white' },
  { w: 'nigra', g: 'adj', e: 'black' },
  // Verbs
  { w: 'ami', g: 'v', e: 'to love' },
  { w: 'odi', g: 'v', e: 'to hate' },
  { w: 'vidi', g: 'v', e: 'to see' },
  { w: 'aŭdi', g: 'v', e: 'to hear' },
  { w: 'legi', g: 'v', e: 'to read' },
  { w: 'skribi', g: 'v', e: 'to write' },
  { w: 'paroli', g: 'v', e: 'to speak' },
  { w: 'pensi', g: 'v', e: 'to think' },
  { w: 'scii', g: 'v', e: 'to know' },
  { w: 'kompreni', g: 'v', e: 'to understand' },
  { w: 'fari', g: 'v', e: 'to do/make' },
  { w: 'iri', g: 'v', e: 'to go' },
  { w: 'veni', g: 'v', e: 'to come' },
  { w: 'esti', g: 'v', e: 'to be' },
  { w: 'havi', g: 'v', e: 'to have' },
  { w: 'donaci', g: 'v', e: 'to give' },
  { w: 'preni', g: 'v', e: 'to take' },
  { w: 'povi', g: 'v', e: 'to be able' },
  { w: 'voli', g: 'v', e: 'to want' },
  { w: 'devi', g: 'v', e: 'to must/have to' },
  { w: 'manĝi', g: 'v', e: 'to eat' },
  { w: 'trinki', g: 'v', e: 'to drink' },
  { w: 'dormi', g: 'v', e: 'to sleep' },
  { w: 'veki', g: 'v', e: 'to wake' },
  { w: 'marŝi', g: 'v', e: 'to walk' },
  { w: 'kuri', g: 'v', e: 'to run' },
  { w: 'dancii', g: 'v', e: 'to dance' },
  { w: 'kanti', g: 'v', e: 'to sing' },
  { w: 'ludi', g: 'v', e: 'to play' },
  { w: 'labori', g: 'v', e: 'to work' },
  // Function Words
  { w: 'kaj', g: 'conj', e: 'and' },
  { w: 'sed', g: 'conj', e: 'but' },
  { w: 'aŭ', g: 'conj', e: 'or' },
  { w: 'ĉar', g: 'conj', e: 'because' },
  { w: 'se', g: 'conj', e: 'if' },
  { w: 'dum', g: 'conj', e: 'while/during' },
  { w: 'ankaŭ', g: 'adv', e: 'also/too' },
  { w: 'ne', g: 'adv', e: 'not' },
  { w: 'ja', g: 'adv', e: 'yes/indeed' },
  { w: 'en', g: 'prep', e: 'in' },
  { w: 'el', g: 'prep', e: 'out of' },
  { w: 'sur', g: 'prep', e: 'on' },
  { w: 'sub', g: 'prep', e: 'under' },
  { w: 'ĉe', g: 'prep', e: 'at/near' },
  { w: 'al', g: 'prep', e: 'to' },
  { w: 'de', g: 'prep', e: 'of/from' },
  { w: 'pro', g: 'prep', e: 'for/because of' },
  { w: 'kontraŭ', g: 'prep', e: 'against' },
  { w: 'per', g: 'prep', e: 'by/through' },
  { w: 'inter', g: 'prep', e: 'between' },
  { w: 'antaŭ', g: 'prep', e: 'before' },
  { w: 'post', g: 'prep', e: 'after' },
  { w: 'apud', g: 'prep', e: 'beside' },
  { w: 'proksime', g: 'adv', e: 'near/close' },
  { w: 'malproksime', g: 'adv', e: 'far' },
  { w: 'ĉiufoje', g: 'adv', e: 'always' },
  { w: 'neniam', g: 'adv', e: 'never' },
  { w: 'iafoje', g: 'adv', e: 'sometimes' },
  { w: 'ĉi', g: 'adv', e: 'this' },
  { w: 'tia', g: 'adj', e: 'such' },
  { w: 'tio', g: 'pron', e: 'that' },
  { w: 'mi', g: 'pron', e: 'I' },
  { w: 'vi', g: 'pron', e: 'you' },
  { w: 'li', g: 'pron', e: 'he' },
  { w: 'ŝi', g: 'pron', e: 'she' },
  { w: 'ĝi', g: 'pron', e: 'it' },
  { w: 'ni', g: 'pron', e: 'we' },
  { w: 'ili', g: 'pron', e: 'they' },
  { w: 'ĉu', g: 'adv', e: 'whether' },
  { w: 'kiu', g: 'pron', e: 'who' },
  { w: 'kio', g: 'pron', e: 'what' },
  { w: 'kia', g: 'adj', e: 'what kind' },
  { w: 'kiom', g: 'adv', e: 'how much' },
  { w: 'kie', g: 'adv', e: 'where' },
  { w: 'kiel', g: 'adv', e: 'how' },
  { w: 'kiam', g: 'adv', e: 'when' },
];
